# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-10 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_article', models.BooleanField()),
                ('is_blog', models.BooleanField()),
                ('is_news', models.BooleanField()),
                ('foreign_id', models.IntegerField()),
            ],
        ),
    ]
