# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 03:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180209_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
