# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 03:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_feature_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='foreign_reference_number',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
