# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 20:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('reference_number', models.CharField(max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6)])),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archetype_name', models.CharField(max_length=20, unique=True)),
                ('main_color', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7)])),
                ('accent_color', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7)])),
            ],
        ),
        migrations.CreateModel(
            name='Pseudonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonym', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='palette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Palette'),
        ),
        migrations.AddField(
            model_name='article',
            name='pseudonym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Pseudonym'),
        ),
        migrations.AddField(
            model_name='article',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Series'),
        ),
    ]
