# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 16:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, unique=True)),
                ('url_string', models.CharField(max_length=500, unique=True)),
                ('reference_number', models.CharField(max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6)])),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('palette_id', models.AutoField(primary_key=True, serialize=False)),
                ('archetype_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pseudonym',
            fields=[
                ('pseudonym_id', models.AutoField(primary_key=True, serialize=False)),
                ('pseudonym', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('series_id', models.AutoField(primary_key=True, serialize=False)),
                ('series_name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='palette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Palette'),
        ),
        migrations.AddField(
            model_name='article',
            name='pseudonym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Pseudonym'),
        ),
        migrations.AddField(
            model_name='article',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Series'),
        ),
    ]
