# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palette',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='palette',
            name='main_color',
        ),
    ]
