# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 01:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180103_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pseudonym',
            name='id',
        ),
        migrations.AlterField(
            model_name='article',
            name='reference_number',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='pseudonym',
            name='pseudonym',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
