# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20180103_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url_string',
            field=models.CharField(default='update me', max_length=500),
            preserve_default=False,
        ),
    ]
