# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_url_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url_string',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
